import 'package:get/get.dart';

class Internet extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          '登录': 'Login',
          '注册': 'Register',
          '退出登录': 'Exit',
          '点击登录': 'Click-To-Login',
          '个人主页': 'HomePage',
          '个人信息': 'Profile',
          '版本：': 'Version：',
          '应用主题': 'Theme',
          '历史记录': 'Records',
          '语言风格': 'Language',
          '给开发者点赞': 'Reward',
          '修改密码': 'Change-Password',
          '关于': 'About',
          '涤纶织物': 'Fabric',
          '纯棉T恤': 'T-shirt',
          '洗衣液': 'Shampoo',
          '白酒': 'Alcohol',
          '啤酒': 'Beer',
          '吸烟': 'Smoke',
          '羊肉': 'Mutton',
          '牛肉': 'Beef',
          '猪肉': 'Pork',
          '炸鸡': 'Fried-Chicken',
          '鸡蛋': 'Egg',
          '土豆': 'Potato',
          '米饭': 'Rice',
          '花生': 'Peanut',
          '酸奶': 'Yogurt',
          '西兰花': 'Broccoli',
          '豆腐': 'Tofu',
          '牛奶': 'Milk',
          '西红柿': 'Tomato',
          '扁豆': 'Lentils',
          '煤': 'Coal',
          '用电': 'Electricity',
          '用水': 'Water',
          '煤气': 'Gas',
          '天然气': 'Natural-Gas',
          '供暖': 'Heating',
          '蜂窝煤': 'Briquettes',
          '液化气': 'Liquefied-gas',
          '飞机': 'Air',
          '火车': 'Train',
          '轮船': 'Ship',
          '地铁': 'Subway',
          '公交车': 'Bus',
          '高耗油汽车': 'High-Cost-Car',
          '中耗油汽车': 'Medium-Cost-Car',
          '低耗油汽车': 'Low-Cost-Car',
          '纸制品': 'PaperProduct',
          '塑料袋': 'PlasticBag',
          '一次性筷子': 'Once-Chopsticks',
          '洗发水': 'Shampoo',
          '玫瑰': 'Rose',
          '城市垃圾': 'Rubbish',
          '加载中...': 'Loading...',
          '登录中...': 'Login...',
          '登录成功,返回主页': 'success',
          '记住密码': 'Remember Password',
          '账号': 'Account',
          '密码': 'Password',
          '注册新账户': 'Register New User',
          '昵称': 'username',
          '邮箱': 'email',
          '验证码': 'confirm',
          '发送验证码': 'send code',
          '发送中': 'sending',
          '输入您的昵称': 'input your username ',
          '输入您的密码': 'input your password',
          '输入您的邮箱': 'input your email address',
          '密码至少6位数': 'length is at least 6',
          '输入您的验证码': 'input your confirm code',
          '验证码不能为空': 'confirm code cannot be null',
          '邮箱不能为空': 'email cannot be null',
          '昵称不能为空': 'username cannot be null',
          '账号不能为空': 'account cannot be null',
          '请耐心等待': 'please waiting for a minute',
          '请先填写邮箱': 'please input your email first',
          '已发送验证码,请勿重复点击': 'have sended code,please don`t click constantly',
          '提醒': 'warning',
          '请检查网络连接': 'check your network',
          '绿色': 'green',
          '蓝色': 'blue',
          '橙色': 'orange',
          '淡青色': 'cyan',
          '红色': 'red',
          '黄色': 'yellow',
          '紫色': 'purple',
          '夜间模式': 'night modern',
          '主题选择': 'Theme Select',
          '确定': 'yes',
          '取消': 'cancel',
          '原密码': 'old password',
          '新密码': 'new password',
          '确认新密码': 'input again to check',
          '原密码不能为空': 'old pass cannot be null',
          '新密码不能为空': 'new pass cannot be null',
          '两次输入不一致': 'twice input is different',
          '密码修改成功，请重新登录': 'change successfully, please login again',
          '计算': 'calculate',
          'C知道': 'AI-C',
          '分析': 'Analyze',
          '我的': 'me',
          'AI聊天': 'AI Chat',
          '碳足迹计算器': 'Carbon Footprint Calculate',
          '衣': 'clothes',
          '食': 'food',
          '住': 'live',
          '行': 'traffic',
          '用': 'consume',
          '数量': 'counts',
          '升': 'L',
          '千克': 'Kg',
          '件': 'jian',
          '瓶': 'bottle',
          '包': 'pack',
          '吨': 't',
          '度': 'kilowatt hour',
          '立方米': 'cubic meter',
          '块': 'pile',
          '平米/天': 'Square meters/day',
          '公里': 'kilometers',
          '个': 'ge',
          '双': 'pair',
          '指': 'zhi',
          '还未选择要计算的产品哦!!!': 'have not selected your target item',
          '开始你的对话吧': 'Start your chat',
          '请输入消息': 'here input message',
          '生成回答中...': 'generating answer...',
          '耗碳类型占比': 'Proportion of carbon consumption types',
          '碳排放种类排行': 'Carbon emission type ranking ',
          '近七日碳排放统计': 'Recently carbon emission',
          '语言选择': 'Language Select',
          '英语': 'English',
          '中文': 'Chinese',
          '当前是最新版本': 'Current version is newest',
          '未登录': 'Login is Null',
          '请先登录': 'Please login first',
          '您确定要退出登录吗':'Do you want to exit really?',
        },
      };
}
